Repository salesagility/SuiteDocs, pull requests merged in 2023-03, with the labels that each got.

#600 Update Summary.adoc
  content/user/introduction/User Interface/Summary.adoc
Labels: Status: Ready to Merge, Passed Code Review

#599 Update Desktop Notifications.adoc
  content/user/introduction/User Interface/Desktop Notifications.adoc
Labels: Status: Ready to Merge, Passed Code Review

#598 Update In-line Editing.adoc
  content/user/introduction/User Interface/In-line Editing.adoc
Labels: Status: Ready to Merge, Passed Code Review

#596 Update Views.adoc
  content/user/introduction/User Interface/Views.adoc
Labels: Status: Ready to Merge, Passed Code Review

#594 Update Home Page.adoc
  content/user/introduction/User Interface/Home Page.adoc
Labels: Status: Ready to Merge, Passed Code Review

#593 Update Forking.adoc
  content/community/contributing-code/Forking.adoc
Labels: Status: Ready to Merge, Passed Code Review

#592 Update Navigation Elements.adoc
  content/user/introduction/User Interface/Navigation Elements.adoc
Labels: Status: Ready to Merge, Passed Code Review

#591 Update managing-user-accounts.adoc
  content/user/introduction/managing-user-accounts.adoc
Labels: Status: Ready to Merge, Passed Code Review

#590 Update User Wizard.adoc
  content/user/introduction/User Wizard.adoc
Labels: Status: Ready to Merge, Passed Code Review

#589 Update Getting Started.adoc
  content/user/introduction/Getting Started.adoc
Labels: Status: Ready to Merge, Passed Code Review

#588 Update _index.en.adoc
  content/user/introduction/_index.en.adoc
Labels: Status: Ready to Merge, Passed Code Review

#587 Update Sass Documentation
  content/developer/Theme/sass.adoc
Labels: Status: Ready to Merge, Passed Code Review

#586 Update API docs and change contents order
  content/developer/api/Developer-setup-guide/Configure Authentication.adoc
  content/developer/api/Developer-setup-guide/Getting Available Resources.adoc
  content/developer/api/Developer-setup-guide/JSON-API.adoc
  content/developer/api/Developer-setup-guide/SuiteCRM_V8_API_Set_Up_For_Postman.adoc
Labels: Status: Ready to Merge, Passed Code Review

#585 Adding notice to keep v8 users from getting lost in v7 space
  content/admin/installation-guide/Downloading & Installing.adoc
Labels: Status: Ready to Merge, Status:Assessed, Passed Code Review

#583 Update README.md for typo
  README.md
Labels: Status: Ready to Merge, Hacktoberfest, Status:Assessed, Passed Code Review

#576 Update JSON-API.adoc
  content/developer/api/Developer-setup-guide/JSON-API.adoc
Labels: Status: Ready to Merge, Status:Assessed, Passed Code Review

#281 add after_load_user logic hook
  content/developer/Logic Hooks.adoc
Labels: Status: Ready to Merge, Passed Code Review

#595 Update Search.adoc
  content/user/introduction/User Interface/Search.adoc
Labels: Status: Ready to Merge, Passed Code Review
